<?php 

class view_layout_default{ 

public function M($V){ 
extract($V);
$_ ='';
$_ .= '<!DOCTYPE html> <html> <head> ';
$_ .= $this->head($V);
$_ .= '</head> <body> ';
$_ .= $this->content($V);
$_ .= '</body> </html>';
return $_;
} 


public function head($V){ 
extract($V);
$_ ='';
$_ .= ' ';
return $_;
} 


public function content($V){ 
extract($V);
$_ ='';
$_ .= ' Please take a look at layout.default ';
return $_;
} 


}  ?><?php 

class view_demo_cache_with_dynamic extends view_layout_default{ 

public function M($V){ 
  return parent::M($V);
} 


public function head($V){ 
extract($V);
$_ ='';
$_ .= ' ';
return $_;
} 


public function content($V){ 
extract($V);
$_ ='';
$_ .= ' <table border="1" width="100%"> <tr> <td><b>Clock:';
 $_ .=  date('Y-m-d H:i:s') ; 
$_ .= '</b></td> </tr> <tr> <td height="150">';
 $_ .=  $content ; 
$_ .= '</td> </tr> <tr> <td>Email: yangqingrong';
$_ .='@'; 
$_ .= 'wudimei.com</td> </tr> </table> ';
return $_;
} 


}  ?>