<?php 

class view_components_nav{ 

public function M($V){ 
extract($V);
$_ ='';
$_ .= '<nav style="background-color:#E8E8E8;"> ';
 $_ .=  htmlspecialchars($date); 
$_ .= ' ';
 $_ .=  htmlspecialchars($title); 
$_ .= ' </nav>';
return $_;
} 


}  ?><?php 

class view_layout_default{ 

public function M($V){ 
extract($V);
$_ ='';
$_ .= '<!DOCTYPE html> <html> <head> ';
$_ .= $this->head($V);
$_ .= '</head> <body> ';
$_ .= $this->content($V);
$_ .= '</body> </html>';
return $_;
} 


public function head($V){ 
extract($V);
$_ ='';
$_ .= ' ';
return $_;
} 


public function content($V){ 
extract($V);
$_ ='';
$_ .= ' Please take a look at layout.default ';
return $_;
} 


}  ?><?php 

class view_demo_extends extends view_layout_default{ 

public function M($V){ 
  return parent::M($V);
} 


public function head($V){ 
extract($V);
$_ ='';
$_ .= ' ';
return $_;
} 


public function content($V){ 
extract($V);
$_ ='';
$_ .= ' ';
$inc_args =['components.nav',['date' => '2020-10-07','title'=>$title]];

$inc_obj =new view_components_nav();

$_ .=$inc_obj->M($inc_args[1]);


$_ .= ' <h1> ';
 $_ .=  htmlspecialchars($title); 
$_ .= ' </h1> <table border="1"> ';
 if( !empty($data)){foreach($data as $row){ 
$_ .= ' ';
 if( $row->id > 0 ){  
$_ .= ' <tr> <td>';
 $_ .=  htmlspecialchars($row->id ); 
$_ .= '</td> <td>';
 $_ .= $row->name; 
$_ .= '</td> </tr> ';
 } 
 }} 
$_ .= '</table> Email: yangqingrong';
$_ .='@'; 
$_ .= 'wudimei.com ';
return $_;
} 


}  ?>